// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RPI_Task.Presistences;

namespace RPI_Task.Migrations
{
    [DbContext(typeof(notification_context))]
    [Migration("20200316122033_initialcreatemigrationsdb")]
    partial class initialcreatemigrationsdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RPI_Task.Domain.Entities.NotificationTB", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("created_at")
                        .HasColumnType("bigint");

                    b.Property<string>("message")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<long>("updated_at")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("RPI_Task.Domain.Entities.Notification_logsTB", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("create_at")
                        .HasColumnType("bigint");

                    b.Property<string>("email_destination")
                        .HasColumnType("text");

                    b.Property<int>("from")
                        .HasColumnType("integer");

                    b.Property<int>("notification_id")
                        .HasColumnType("integer");

                    b.Property<long>("read_at")
                        .HasColumnType("bigint");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.Property<long>("update_at")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("notification_id");

                    b.ToTable("Notification_Logs");
                });

            modelBuilder.Entity("RPI_Task.Domain.Entities.Target", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Notification_logsTBid")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Notification_logsTBid");

                    b.ToTable("Target");
                });

            modelBuilder.Entity("RPI_Task.Domain.Entities.Notification_logsTB", b =>
                {
                    b.HasOne("RPI_Task.Domain.Entities.NotificationTB", "notification")
                        .WithMany()
                        .HasForeignKey("notification_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RPI_Task.Domain.Entities.Target", b =>
                {
                    b.HasOne("RPI_Task.Domain.Entities.Notification_logsTB", null)
                        .WithMany("target")
                        .HasForeignKey("Notification_logsTBid");
                });
#pragma warning restore 612, 618
        }
    }
}
